In [1]:
import pandas as pd
from mlxtend.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("wine.csv")
df

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [3]:
df.isnull().sum()

Wine                    0
Alcohol                 0
Malic.acid              0
Ash                     0
Acl                     0
Mg                      0
Phenols                 0
Flavanoids              0
Nonflavanoid.phenols    0
Proanth                 0
Color.int               0
Hue                     0
OD                      0
Proline                 0
dtype: int64

In [4]:
X = df.iloc[:, 1:14]
y = df['Wine']
X

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=100)

In [6]:
#cv is cross validatioin
bakward_feature_selector = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
                                                    k_features=8,
                                                    forward=False,
                                                    floating=False,
                                                    verbose=2,
                                                    scoring= "accuracy",
                                                    cv= 5).fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    9.3s finished

[2023-05-13 21:12:44] Features: 12/8 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    7.4s finished

[2023-05-13 21:12:51] Features: 11/8 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    7.3s finished

[2023-05-13 21:12:59] Features: 10/8 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    6.9s finished

[2023-05-13 21:13:05] Features: 9/8 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    6.1s finished

[2023-05-13 21:13:12] Features: 8/8 -- score: 0.992

In [7]:
bakward_feature_selector.k_feature_idx_

(0, 1, 3, 4, 5, 6, 9, 12)

In [8]:
bakward_feature_selector.k_feature_names_

('Alcohol',
 'Malic.acid',
 'Acl',
 'Mg',
 'Phenols',
 'Flavanoids',
 'Color.int',
 'Proline')

In [9]:
bakward_feature_selector.k_score_

0.992

In [10]:
bakward_feature_selector = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
                                                    k_features=(1,13),
                                                    forward=False,
                                                    floating=False,
                                                    verbose=2,
                                                    scoring= "accuracy",
                                                    cv= 5).fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:   10.7s finished

[2023-05-13 21:14:47] Features: 12/1 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    7.7s finished

[2023-05-13 21:14:55] Features: 11/1 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    7.1s finished

[2023-05-13 21:15:02] Features: 10/1 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    6.5s finished

[2023-05-13 21:15:09] Features: 9/1 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    5.8s finished

[2023-05-13 21:15:15] Features: 8/1 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    5.0s finished

[2023-05-13 21:15:20] Features: 7/1 -- score: 0.992[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    4.2s finished

[2023-05-13 21:15:24] Features: 6/1 -- score: 0.984[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    3.7s finished

[2023-05-13 21:15:28] Features: 5/1 -- score: 0.976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    3.1s finished

[2023-05-13 21:15:31] Features: 4/1 -- score: 0.976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    2.5s finished

[2023-05-13 21:15:34] Features: 3/1 -- score: 0.9596666666666666[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.7s finished

[2023-05-13 21:15:36] Features: 2/1 -- score: 0.9433333333333334[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.1s finished

[2023-05-13 21:15:37] Features: 1/1 -- score: 0.7743333333333333

In [12]:
bakward_feature_selector.k_score_

0.992

In [11]:
pd.DataFrame.from_dict(bakward_feature_selector.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
13,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984,"(Alcohol, Malic.acid, Ash, Acl, Mg, Phenols, F...",0.025186,0.019596,0.009798
12,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12)","[0.96, 1.0, 0.96, 1.0, 1.0]",0.984,"(Alcohol, Malic.acid, Ash, Acl, Mg, Phenols, F...",0.025186,0.019596,0.009798
11,"(0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992,"(Alcohol, Malic.acid, Acl, Mg, Phenols, Flavan...",0.020565,0.016,0.008
10,"(0, 1, 3, 4, 5, 6, 7, 9, 10, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992,"(Alcohol, Malic.acid, Acl, Mg, Phenols, Flavan...",0.020565,0.016,0.008
9,"(0, 1, 3, 4, 5, 6, 9, 10, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992,"(Alcohol, Malic.acid, Acl, Mg, Phenols, Flavan...",0.020565,0.016,0.008
8,"(0, 1, 4, 5, 6, 9, 10, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992,"(Alcohol, Malic.acid, Mg, Phenols, Flavanoids,...",0.020565,0.016,0.008
7,"(0, 1, 4, 5, 6, 9, 12)","[0.96, 1.0, 1.0, 1.0, 1.0]",0.992,"(Alcohol, Malic.acid, Mg, Phenols, Flavanoids,...",0.020565,0.016,0.008
6,"(0, 4, 5, 6, 9, 12)","[0.96, 0.96, 1.0, 1.0, 1.0]",0.984,"(Alcohol, Mg, Phenols, Flavanoids, Color.int, ...",0.025186,0.019596,0.009798
5,"(0, 4, 6, 9, 12)","[0.96, 0.96, 1.0, 0.96, 1.0]",0.976,"(Alcohol, Mg, Flavanoids, Color.int, Proline)",0.025186,0.019596,0.009798
4,"(0, 6, 9, 12)","[0.96, 0.96, 0.96, 1.0, 1.0]",0.976,"(Alcohol, Flavanoids, Color.int, Proline)",0.025186,0.019596,0.009798
3,"(6, 9, 12)","[0.92, 1.0, 0.96, 0.96, 0.9583333333333334]",0.959667,"(Flavanoids, Color.int, Proline)",0.032527,0.025307,0.012654
2,"(6, 9)","[0.92, 1.0, 1.0, 0.88, 0.9166666666666666]",0.943333,"(Flavanoids, Color.int)",0.062145,0.048351,0.024175
1,"(6,)","[0.76, 0.76, 0.76, 0.8, 0.7916666666666666]",0.774333,"(Flavanoids,)",0.022816,0.017751,0.008876