In [11]:
import pandas as pd
from mlxtend.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [4]:
df = pd.read_csv("wine.csv")
df

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [5]:
df.isnull().sum()

Wine                    0
Alcohol                 0
Malic.acid              0
Ash                     0
Acl                     0
Mg                      0
Phenols                 0
Flavanoids              0
Nonflavanoid.phenols    0
Proanth                 0
Color.int               0
Hue                     0
OD                      0
Proline                 0
dtype: int64

In [13]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Wine, Alcohol, Malic.acid, Ash, Acl, Mg, Phenols, Flavanoids, Nonflavanoid.phenols, Proanth, Color.int, Hue, OD, Proline]
Index: []

In [28]:
X = df.iloc[:, 1:14]
y = df['Wine']
X

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=100)

In [30]:
#cv is cross validatioin
forward_feature_selection = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
                                                     k_features= 6,
                                                     forward=True,
                                                     floating=False,
                                                     verbose=2,
                                                     scoring= "accuracy",
                                                     cv= 5).fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:   10.9s finished

[2023-05-13 20:47:20] Features: 1/6 -- score: 0.7906666666666667[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    7.5s finished

[2023-05-13 20:47:27] Features: 2/6 -- score: 0.9353333333333333[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    7.0s finished

[2023-05-13 20:47:34] Features: 3/6 -- score: 0.976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    6.3s finished

[2023-05-13 20:47:41] Features: 4/6 -- score: 0.976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    5.5s finished

[2023-05-13 20:47:46] Features: 5/6 -- score: 0.976[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    5.0s finished

[2023-05-13 20:47:51] Features: 6/6 -- score: 0.992

In [31]:
forward_feature_selection.k_feature_names_

('Malic.acid',
 'Mg',
 'Phenols',
 'Flavanoids',
 'Nonflavanoid.phenols',
 'Color.int')

In [32]:
forward_feature_selection.k_score_

0.992

In [33]:
pd.DataFrame.from_dict(forward_feature_selection.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(6,)","[0.76, 0.76, 0.8, 0.8, 0.8333333333333334]",0.790667,"(Flavanoids,)",0.035784,0.027841,0.01392
2,"(6, 9)","[0.92, 0.96, 1.0, 0.88, 0.9166666666666666]",0.935333,"(Flavanoids, Color.int)",0.052793,0.041074,0.020537
3,"(4, 6, 9)","[1.0, 1.0, 1.0, 0.88, 1.0]",0.976,"(Mg, Flavanoids, Color.int)",0.061694,0.048,0.024
4,"(4, 5, 6, 9)","[0.96, 1.0, 1.0, 0.92, 1.0]",0.976,"(Mg, Phenols, Flavanoids, Color.int)",0.041129,0.032,0.016
5,"(1, 4, 5, 6, 9)","[1.0, 1.0, 1.0, 0.88, 1.0]",0.976,"(Malic.acid, Mg, Phenols, Flavanoids, Color.int)",0.061694,0.048,0.024
6,"(1, 4, 5, 6, 7, 9)","[1.0, 1.0, 1.0, 0.96, 1.0]",0.992,"(Malic.acid, Mg, Phenols, Flavanoids, Nonflava...",0.020565,0.016,0.008

In [34]:
forward_feature_selection = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
                                                     k_features= (1,13),
                                                     forward=True,
                                                     floating=False,
                                                     verbose=2,
                                                     scoring= "accuracy",
                                                     cv= 4).fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    9.1s finished

[2023-05-13 20:48:46] Features: 1/13 -- score: 0.7580645161290323[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    6.8s finished

[2023-05-13 20:48:53] Features: 2/13 -- score: 0.9354838709677419[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    5.6s finished

[2023-05-13 20:48:59] Features: 3/13 -- score: 0.9596774193548387[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    5.2s finished

[2023-05-13 20:49:04] Features: 4/13 -- score: 0.9758064516129032[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    4.4s finished

[2023-05-13 20:49:08] Features: 5/13 -- score: 0.9758064516129032[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    4.1s finished

[2023-05-13 20:49:13] Features: 6/13 -- score: 0.9838709677419355[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    3.4s finished

[2023-05-13 20:49:16] Features: 7/13 -- score: 0.9838709677419355[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    3.2s finished

[2023-05-13 20:49:19] Features: 8/13 -- score: 0.9919354838709677[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    2.7s finished

[2023-05-13 20:49:22] Features: 9/13 -- score: 0.9838709677419355[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    2.0s finished

[2023-05-13 20:49:24] Features: 10/13 -- score: 0.9838709677419355[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.4s finished

[2023-05-13 20:49:26] Features: 11/13 -- score: 0.9838709677419355[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.0s finished

[2023-05-13 20:49:27] Features: 12/13 -- score: 0.9758064516129032[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s finished

[2023-05-13 20:49:27] Features: 13/13 -- score: 0.9758064516129032

In [35]:
pd.DataFrame.from_dict(forward_feature_selection.get_metric_dict()).T

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(6,)","[0.6774193548387096, 0.7741935483870968, 0.806...",0.758065,"(Flavanoids,)",0.077564,0.048387,0.027936
2,"(6, 12)","[0.9032258064516129, 0.9354838709677419, 0.935...",0.935484,"(Flavanoids, Proline)",0.036564,0.02281,0.013169
3,"(6, 9, 12)","[0.9354838709677419, 0.967741935483871, 1.0, 0...",0.959677,"(Flavanoids, Color.int, Proline)",0.042875,0.026747,0.015442
4,"(2, 6, 9, 12)","[0.967741935483871, 0.967741935483871, 1.0, 0....",0.975806,"(Ash, Flavanoids, Color.int, Proline)",0.022391,0.013968,0.008065
5,"(0, 2, 6, 9, 12)","[0.967741935483871, 0.967741935483871, 1.0, 0....",0.975806,"(Alcohol, Ash, Flavanoids, Color.int, Proline)",0.022391,0.013968,0.008065
6,"(0, 2, 3, 6, 9, 12)","[0.967741935483871, 1.0, 1.0, 0.967741935483871]",0.983871,"(Alcohol, Ash, Acl, Flavanoids, Color.int, Pro...",0.025855,0.016129,0.009312
7,"(0, 2, 3, 6, 8, 9, 12)","[0.967741935483871, 1.0, 1.0, 0.967741935483871]",0.983871,"(Alcohol, Ash, Acl, Flavanoids, Proanth, Color...",0.025855,0.016129,0.009312
8,"(0, 2, 3, 4, 6, 8, 9, 12)","[0.967741935483871, 1.0, 1.0, 1.0]",0.991935,"(Alcohol, Ash, Acl, Mg, Flavanoids, Proanth, C...",0.022391,0.013968,0.008065
9,"(0, 1, 2, 3, 4, 6, 8, 9, 12)","[0.967741935483871, 1.0, 1.0, 0.967741935483871]",0.983871,"(Alcohol, Malic.acid, Ash, Acl, Mg, Flavanoids...",0.025855,0.016129,0.009312
10,"(0, 1, 2, 3, 4, 6, 8, 9, 10, 12)","[0.967741935483871, 1.0, 1.0, 0.967741935483871]",0.983871,"(Alcohol, Malic.acid, Ash, Acl, Mg, Flavanoids...",0.025855,0.016129,0.009312
11,"(0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 12)","[0.967741935483871, 0.967741935483871, 1.0, 1.0]",0.983871,"(Alcohol, Malic.acid, Ash, Acl, Mg, Flavanoids...",0.025855,0.016129,0.009312
12,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12)","[0.967741935483871, 0.967741935483871, 1.0, 0....",0.975806,"(Alcohol, Malic.acid, Ash, Acl, Mg, Phenols, F...",0.022391,0.013968,0.008065
13,"(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)","[0.967741935483871, 0.967741935483871, 0.96774...",0.975806,"(Alcohol, Malic.acid, Ash, Acl, Mg, Phenols, F...",0.022391,0.013968,0.008065

In [36]:
forward_feature_selection.k_score_

0.9919354838709677